/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const AddAssetHtmlPlugin = require('add-asset-html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = require('./webpack.base.babel')({
  mode: 'development',

  // Add hot reloading in development
  entry: [
    require.resolve('react-app-polyfill/ie11'),
    'webpack-hot-middleware/client?reload=true',
    path.join(process.cwd(), 'app/app.js'), // Start with js/app.js
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },

  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'app/index.html',
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
    new AddAssetHtmlPlugin([
      { filepath: require.resolve('../../app/assets/plugins/jquery/jquery.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/jquery-ui/jquery-ui.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/bootstrap/js/bootstrap.bundle.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/bootstrap/js/bootstrap.bundle.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/chart.js/Chart.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/sparklines/sparkline.js') },
      { filepath: require.resolve('../../app/assets/plugins/jqvmap/jquery.vmap.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/jqvmap/maps/jquery.vmap.usa.js') },
      { filepath: require.resolve('../../app/assets/plugins/jquery-knob/jquery.knob.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/moment/moment.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/daterangepicker/daterangepicker.js') },
      { filepath: require.resolve('../../app/assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/summernote/summernote-bs4.min.js') },
      { filepath: require.resolve('../../app/assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') },
      { filepath: require.resolve('../../app/assets/dist/js/adminlte.js') },
      { filepath: require.resolve('../../app/assets/dist/js/pages/dashboard.js') },
      { filepath: require.resolve('../../app/assets/plugins/fontawesome-free/css/all.min.css'), typeOfAsset: 'css' },
      { filepath: require.resolve('../../app/assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'), typeOfAsset: 'css' },
      { filepath: require.resolve('../../app/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css'), typeOfAsset: 'css' },
      { filepath: require.resolve('../../app/assets/plugins/jqvmap/jqvmap.min.css'), typeOfAsset: 'css' },
      { filepath: require.resolve('../../app/assets/dist/css/adminlte.min.css'), typeOfAsset: 'css' },
      { filepath: require.resolve('../../app/assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'), typeOfAsset: 'css' },
      { filepath: require.resolve('../../app/assets/plugins/daterangepicker/daterangepicker.css'), typeOfAsset: 'css' },
      { filepath: require.resolve('../../app/assets/plugins/summernote/summernote-bs4.min.css'), typeOfAsset: 'css' },
    ]),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',

  performance: {
    hints: false,
  },
});
